name: tests

on: [push, pull_request]

jobs:
  sphinx-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7']
    steps:
        - name: Set up Python ${{ matrix.python-version }}
          run: |
            echo $CONDA/bin >> $GITHUB_PATH  # prioritize conda over system python
            conda config --add channels conda-forge
            conda install -y -q python=${{ matrix.python-version }}
        #     conda create -y -q -n test-environment python=${{ matrix.python-version }}
        #     source activate test-environment

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Install package from repository
          run: |
            pip install -e .

        - name: Install extra depenencies
          run: |
            conda install -y -q av
            pip install -r requirements-docs.txt

        - name: Verify Python version
          run: |
            which python
            python --version
            python -c "import os, sys; assert sys.version_info[:2] == tuple(map(int, '${{ matrix.python-version }}'.split('.')))[:2]"

        - name: List pip packages
          run: |
            pip -V
            pip list

        - name: List conda packages
          run: |
            conda env list
            conda list

        - name: Build docs
          run: |
            cd docs
            make html

  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']
    env:
      DISPLAY: ':99.0'

    steps:
        - name: Set up virtual framebuffer (xvfb) for Qt GUI testing
          # https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#github-actions
          run: |
            sudo apt-get install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
            /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX

        - name: Set up Python ${{ matrix.python-version }}
          run: |
            echo $CONDA/bin >> $GITHUB_PATH  # prioritize conda over system python
            conda config --add channels conda-forge
            conda install -y -q python=${{ matrix.python-version }}
        #     conda create -y -q -n test-environment python=${{ matrix.python-version }}
        #     source activate test-environment

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Install package from repository
          run: |
            pip install -e .

        - name: Install extra depenencies
          run: |
            conda install -y -q av
            pip install -r requirements-tests.txt

        - name: Verify Python version
          run: |
            which python
            python --version
            python -c "import os, sys; assert sys.version_info[:2] == tuple(map(int, '${{ matrix.python-version }}'.split('.')))[:2]"

        - name: List pip packages
          run: |
            pip -V
            pip list

        - name: List conda packages
          run: |
            conda env list
            conda list

        - name: Run tests
          run: |
            nosetests --with-coverage --cover-package=neurotic

        - name: Report coverage to Coveralls
          run: coveralls
          env:
            COVERALLS_SERVICE_NAME: github
            COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            COVERALLS_FLAG_NAME: test-linux-${{ matrix.python-version }}
            COVERALLS_PARALLEL: true

  coveralls:
    name: Finish Coveralls
    needs: test-linux
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finish Coveralls
      run: |
        pip3 install --upgrade coveralls
        coveralls --finish
      env:
        COVERALLS_SERVICE_NAME: github
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
